FROM rockylinux/rockylinux:8

# Install some other dependencies for ease of life.
RUN  dnf update -y \
  && dnf install -y wget git \
  && dnf clean all

# Now move the project directory's files into the image. That way, if these
# files change, caching will skip everything before this.
COPY docker/bin/helpers/run-versions.sh /tmp/bin/run-versions.sh

# Print out available package versions for puppet-agent.
ENTRYPOINT ["/tmp/bin/run-versions.sh"]
